name: copy_with_material
description: "Copy with method extensions for material classes"
version: 1.0.0
repository: https://github.com/ArcaneArts/copy_with_material
environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
flutter: